const AppTypes = {
  LOADING: 'LOADING',
  SET_SELECTED_MODULE: 'SET_SELECTED_MODULE',
  SET_CURRENT_DESIGN: 'SET_CURRENT_DESIGN',
  SET_CURRENT_TEMPLATE: 'SET_CURRENT_TEMPLATE',

  SET_MENU_MESSAGE: 'SET_MENU_MESSAGE',
}
export default AppTypes
