const TemplateTypes = {
  LOAD_TEMPLATES_ONE_SCREEN: 'LOAD_TEMPLATES_ONE_SCREEN',

  LOAD_TEMPLATES_TWO_SCREEN: 'LOAD_TEMPLATES_TWO_SCREEN',

  LOAD_TEMPLATES_THREE_SCREEN: 'LOAD_TEMPLATES_THREE_SCREEN',
}

export default TemplateTypes
