const AdminTemplateTypes = {
  ADMIN_LOAD_TEMPLATES_ONE_SCREEN: "ADMIN_LOAD_TEMPLATES_ONE_SCREEN",
  ADMIN_ADD_TEMPLATES_ONE_SCREEN: "ADMIN_ADD_TEMPLATES_ONE_SCREEN",

  ADMIN_LOAD_TEMPLATES_TWO_SCREEN: "ADMIN_LOAD_TEMPLATES_TWO_SCREEN",
  ADMIN_ADD_TEMPLATES_TWO_SCREEN: "ADMIN_ADD_TEMPLATES_TWO_SCREEN",

  ADMIN_LOAD_TEMPLATES_THREE_SCREEN: "ADMIN_LOAD_TEMPLATES_THREE_SCREEN",
  ADMIN_ADD_TEMPLATES_THREE_SCREEN: "ADMIN_ADD_TEMPLATES_THREE_SCREEN",

  ADMIN_SET_SCREEN: "ADMIN_SET_SCREEN",

  ADMIN__SET_TEMPLATE: "ADMIN__SET_TEMPLATE"
};

export default AdminTemplateTypes;
