const AdminDeviceThumbnailTypes = {
  ADMIN_ADD_DEVICE_THUMBNAIL: "ADMIN_ADD_DEVICE_THUMBNAIL",

  ADMIN_SET_DEVICE_THUMBNAIL: "ADMIN_SET_DEVICE_THUMBNAIL",

  ADMIN_GET_DEVICE_THUMBNAILS: "ADMIN_GET_DEVICE_THUMBNAILS"
};

export default AdminDeviceThumbnailTypes;
