const AdminDevicesTypes = {
  ADMIN_LOAD_DEVICES: "ADMIN_LOAD_DEVICES",

  ADMIN_ADD_DEVICES: "ADMIN_ADD_DEVICES",

  ADMIN_ADD_DEVICES_CANVAS: "ADMIN_ADD_DEVICES_CANVAS",

  ADMIN_ADD_DEVICE_THUMBNAIL: "ADMIN_ADD_DEVICE_THUMBNAIL",

  ADMIN_RESET_DEVICES_CANVAS: "ADMIN_RESET_DEVICES_CANVAS",

  ADMIN_SET_DEVICE: "ADMIN_SET_DEVICE",

  ADMIN_UPDATE_DEVICE_CANVAS: "ADMIN_UPDATE_DEVICE_CANVAS",

  ADMIN_GET_DEVICE_THUMBNAILS: "ADMIN_GET_DEVICE_THUMBNAILS"
};

export default AdminDevicesTypes;
