const AdminAppTypes = {
  ADMIN_SET_SELECTED_MODULE: "ADMIN_SET_SELECTED_MODULE",
  ADMIN_SET_DEVICE_THUMBNAIL: "ADMIN_SET_DEVICE_THUMBNAIL",
  ADMIN_SET_SCREEN_TYPE: "ADMIN_SET_SCREEN_TYPE",
  ADMIN_SET_SELECTED_DEVICE: "ADMIN_SET_SELECTED_DEVICE",
  ADMIN_SET_SELECTED_TEXT: "ADMIN_SET_SELECTED_TEXT"
};

export default AdminAppTypes;
