const AppTypes = {
  LOADING: 'LOADING',
  SET_SELECTED_MODULE: 'SET_SELECTED_MODULE',
  SET_CURRENT_DESIGN: 'SET_CURRENT_DESIGN',
  SET_CURRENT_TEMPLATE: 'SET_CURRENT_TEMPLATE',

  SET_MENU_MESSAGE: 'SET_MENU_MESSAGE',
  SET_SAVING: 'SET_SAVING',
  SET_THUMBNAIL: 'SET_THUMBNAIL',
};

export default AppTypes
