const BackgroundTypes = {
  GET_ALL: "GET_ALL",

  SET_BACKGROUND: "SET_BACKGROUND",
  SET_BACKGROUND_TYPE: "SET_BACKGROUND_TYPE",

  SET_GRADIENT_COLOR_START: "SET_GRADIENT_COLOR_START",
  SET_GRADIENT_COLOR_END: "SET_GRADIENT_COLOR_END",

  SET_GRADIENT_COLOR_SELECTED: "SET_GRADIENT_COLOR_SELECTED",

  RESET_BACKGROUND_STATE: "RESET_BACKGROUND_STATE"
};
export default BackgroundTypes;
