const ImagesTypes = {
  ADD_IMAGE_MENU: 'ADD_IMAGE_MENU',
  ADD_IMAGE_CANVAS: 'ADD_IMAGE_CANVAS',

  REMOVE_IMAGE_MENU: 'REMOVE_IMAGE_MENU',
  REMOVE_IMAGE_CANVAS: 'REMOVE_IMAGE_CANVAS',
  UPDATE_IMAGE_CANVAS: 'UPDATE_IMAGE_CANVAS',
  SET_IMAGE_CANVAS_SELECTED: 'SET_IMAGE_CANVAS_SELECTED',

  RESET_IMAGES_STATE: 'RESET_IMAGES_STATE',
}

export default ImagesTypes
