const ScreensTypes = {
  ADD_SCREEN_MENU: "ADD_SCREEN_MENU",
  REMOVE_SCREEN: "REMOVE_SCREEN",

  ADD_SCREEN_CANVAS: "ADD_SCREEN_CANVAS",
  REMOVE_SCREEN_CANVAS: "REMOVE_SCREEN_CANVAS",

  REMOVE_IMAGE_STATE: "REMOVE_IMAGE_STATE",

  RESET_SCREENS_STATE: "RESET_SCREENS_STATE"
};

export default ScreensTypes;
