const TemplateTypes = {
  LOAD_TEMPLATES_ONE_SCREEN: 'LOAD_TEMPLATES_ONE_SCREEN',

  LOAD_TEMPLATES_TWO_SCREEN: 'LOAD_TEMPLATES_TWO_SCREEN',

  LOAD_TEMPLATES_THREE_SCREEN: 'LOAD_TEMPLATES_THREE_SCREEN',

  ADD_TEMPLATE: 'ADD_TEMPLATE',

  GET_TEMPLATES: 'GET_TEMPLATES',
  UPDATE_TEXT_TEMPLATE: 'UPDATE_TEXT_TEMPLATE',
}

export default TemplateTypes
