const TextTypes = {
  SET_EDITING_TEXT: 'SET_EDITING_TEXT',
  SET_DRAGGABLE: 'SET_DRAGGABLE',
  ADD_TEXT: 'ADD_TEXT',
  UPDATE_TEXT: 'UPDATE_TEXT',
  DELETE_TEXT: 'DELETE_TEXT',
  RESET_TEXTS_STATE: 'RESET_TEXTS_STATE',
  LOAD_TEXTS: 'LOAD_TEXTS',
};

export default TextTypes
